os: linux
dist: bionic

language: c

install:
    - sudo apt-get update
    - sudo apt-get -y install build-essential autoconf libzstd1-dev libssl-dev dpkg-dev debhelper fakeroot
    - ./autogen.sh
    - ./configure

script:
    - make
    - pushd packages/debian
    - ./configure
    - make
    - popd
