os: linux
dist: bionic

language: c

install:
    - sudo apt-get update
    - sudo apt-get -y install build-essential autoconf libzstd1-dev libssl-dev
    - ./autogen.sh
    - ./configure

script:
    - make
    - cd packages/debian && ./configure
    - cd packages/debian && make
